version: "3.9"
services:
  web:
    build: . # uses the image thjatas built in from the Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine" # public Redis image from Docker Hub